settings:
  title: 'Status Page - Jonathan Beckman'
  url: 'https://status.jonbeckman.com'
  logo: profile.jpg # image in ./public/ folder
  daysInHistogram: 90
  collectResponseTimes: true

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Potential Service Disruption'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: jonbeckman-com
    name: jonbeckman.com
    description: 'Personal website and blog'
    url: 'https://jonbeckman.com/'
    method: GET
    expectStatus: 200
    followRedirect: false

  - id: homeassistant-jonbeckman-com
    name: ha.jonbeckman.com
    description: 'Smart Home'
    url: 'https://ha.jonbeckman.com'
    method: GET
    expectStatus: 200
    linkable: false

  - id: tuffdao-io
    name: tuffdao.io
    description: "The World's First VBT"
    url: 'https://tuffdao.io'
    method: GET
    expectStatus: 200
